#!/bin/bash

echo "------ HOOK START - BUILD -------"
#SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
#SOURCE_COMMIT: the SHA1 hash of the commit being tested.
#COMMIT_MSG: the message from the commit being tested and built.
#DOCKER_REPO: the name of the Docker repository being built.
#DOCKERFILE_PATH: the dockerfile currently being built.
#CACHE_TAG: the Docker repository tag being built.
#IMAGE_NAME: the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:CACHE_TAG.)

echo "Build hook running"

make build

echo "------ HOOK END - BUILD -------"
